name: Waka Readme

on:
  workflow_dispatch: # It is for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # Runs at every 12AM UTC

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.9
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Following flags are required, only if this is not on
          # Profile readme, remove the leading `#` to use them
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>