name: Waka Readme

on:
  workflow_dispatch: # It is for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # Runs at every 12AM UTC

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKATIME_ACCESS_TOKEN }}
          # REPOSITORY: <rafaelaqfc/rafaelaqfc>
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          